name: Generate Responsive Images

on:
  push:
    paths:
      - 'images/src/**'  # Only trigger when files in images/src directory change
    branches: [ main ]
  pull_request:
    paths:
      - 'images/src/**'  # Only trigger when files in images/src directory change
    branches: [ main ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          npm install -g sharp-cli
          npm install -g @squoosh/cli

      - name: Process images
        run: |
          mkdir -p images/processed

          # Find all image files in the src directory
          find images/src -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | while read -r file; do
            # Get the filename without path
            filename=$(basename "$file")
            name="${filename%.*}"
            ext="${filename##*.}"

            # Create responsive versions
            sharp -i "$file" -o "images/processed/${name}-small.${ext}" resize 480
            sharp -i "$file" -o "images/processed/${name}-medium.${ext}" resize 768
            sharp -i "$file" -o "images/processed/${name}-large.${ext}" resize 1200

            # Create optimized original
            squoosh-cli --mozjpeg '{"quality":85}' -d "images/processed" "$file"
          done

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images/processed
          git commit -m "Generate responsive images" || echo "No changes to commit"
          git push